[package]
name = "safe-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hybrid-array = "0.1.0"
typenum = "1.16.0"

[dev-dependencies]
trybuild = {version = "1.0.77", features = ["diff"]}
